// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		CreateChoreModal: typeof import('./src/components/Homework/CreateChoreModal.vue')['default'];
		ExtensionPanel: typeof import('./src/components/Homework/ExtensionPanel.vue')['default'];
		Loading: typeof import('./src/components/Loading.vue')['default'];
		NavBar: typeof import('./src/components/NavBar.vue')['default'];
		NButton: typeof import('naive-ui')['NButton'];
		NCheckbox: typeof import('naive-ui')['NCheckbox'];
		NCollapse: typeof import('naive-ui')['NCollapse'];
		NCollapseItem: typeof import('naive-ui')['NCollapseItem'];
		NDatePicker: typeof import('naive-ui')['NDatePicker'];
		NDivider: typeof import('naive-ui')['NDivider'];
		NDropdown: typeof import('naive-ui')['NDropdown'];
		NDynamicInput: typeof import('naive-ui')['NDynamicInput'];
		NIcon: typeof import('naive-ui')['NIcon'];
		NInput: typeof import('naive-ui')['NInput'];
		NInputNumber: typeof import('naive-ui')['NInputNumber'];
		NModal: typeof import('naive-ui')['NModal'];
		NTag: typeof import('naive-ui')['NTag'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
	}
}

export {};
